[package]
name = "colors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
config = { path = "../../../config" }

# Static dispatch
static-dispatch = { path = "../../../libs/static-dispatch" }

# Common libraries
parallel-processor = "0.1.0"
streaming-libdeflate-rs = "0.1.0"
nightly-quirks = "0.1.0"

# Common pipeline libraries
hashes = { path = "../hashes" }
io = { path = "../io" }
structs = { path = "../structs" }

# Other libraries
typenum = "1.15.0"
hashbrown = "0.12.3"
dashmap = "5.4.0"
byteorder = "1.4.3"
siphasher = "0.3.10"
desse = "0.2.1"
replace_with = "0.1.7"
bstr = "1.0.1"
atoi = "1.0.0"
crossbeam = "0.8.2"
rayon = "1.5.3"
rand = "0.8.5"
roaring = "0.10.1"
parking_lot = "0.12.1"
serde = "1.0.145"
lz4 = "1.24.0"
bincode = "1.3.3"
itertools = "0.10.5"
