[package]
name = "colors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
config = { path = "../../../config" }

# Common libraries
parallel-processor = { path = "../../../libs/parallel-processor-rs" }
libdeflate-rs = { path = "../../../libs/libdeflate-rs" }
nightly-quirks = { path = "../../../libs/nightly-quirks" }

# Common pipeline libraries
hashes = { path = "../hashes" }
io = { path = "../io" }
structs = { path = "../structs" }

# Other libraries
typenum = "1.15.0"
hashbrown = "0.12.1"
dashmap = "5.3.4"
byteorder = "1.4.3"
siphasher = "0.3.10"
desse = "0.2.1"
replace_with = "0.1.7"
bstr = "0.2.17"
atoi = "1.0.0"
crossbeam = "0.8.1"
rayon = "1.5.3"
rand = "0.8.5"
roaring = "0.9.0"
parking_lot = "0.12.1"
serde = "1.0.137"
lz4 = "1.23.3"
bincode = "1.3.3"
