[package]
name = "ggcat_structs"
version = "0.1.0"
edition = "2021"
[dependencies]
bincode = "1.3.3"
config = { package = "ggcat_config", path = "../config" }
io = { package = "ggcat_io", path = "../io" }
parallel-processor = "0.1.7"
serde = { version = "1.0.163", features = ["derive"] }
