[package]
authors = ["Andrea Cracco <guilucand@gmail.com>"]
edition = "2018"
name = "BiLoki"
version = "0.1.0"
[dependencies]
bincode = "1.3.3"
bio = "0.30.0"
bstr = "0.2.8"
byteorder = "1.3.2"
ctrlc = "3.1.3"
itertools = "0.10.0"
lazy_static = "1.4.0"
lz4 = "1.23.1"
nix = "0.15.0"
object-pool = "0.5.3"
os_pipe = "0.9.1"
postcard = "0.4.2"
rayon = "1.3.0"
serde = "1.0.102"
stopwatch = "0.0.7"
structopt = "0.3.5"
pad = "0.1.6"
bitvec = "0.22.3"
hashbrown = "=0.11.2"
rand_pcg = "0.3.0"
rand = "0.8.3"
libdeflater = "0.7.1"
libc = "0.2.94"
threadpool = "1.8.1"
filebuffer = "0.4.0"
crossbeam = "0.8.0"
clap = "2.33.3"
parallel-processor = { path = "parallel-processor-rs" }
rand_chacha = "0.3.1"
fdlimit = "0.2.1"
parking_lot = "0.11.1"
num = "0.4.0"
pcg_rand = "0.13.0"
dashmap = { version = "4.0.2", features = ["serde"] }
serde_json = "1.0.68"

[dependencies.flate2]
default-features = false
features = ["cloudflare_zlib"]
path = "flate2-rs"

[profile.release]
debug = true
