[package]
name = "genome-assembly"
version = "0.1.0"
authors = ["Andrea Cracco <guilucand@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "0.30.0"
stopwatch = "0.0.7"
serde = "1.0.102"
bincode = "1.2.0"
lazy_static = "1.4.0"
postcard = "0.4.2"
byteorder = "1.3.2"
flate2 = "1.0.13"
#rolling-crc = { path = "rolling-crc-rs" }
nthash = { path = "nthash" }
rand = "0.7.2"
nix = "0.15.0"
lz4 = "1.23.1"
os_pipe = "0.9.1"
structopt = "0.3.5"
ctrlc = "3.1.3"
itertools = "0.8.2"
bstr = "0.2.8"
rayon = "1.3.0"
