
cargo-features = ["profile-rustflags"]

[workspace]

members = [
    # Main crate for the command line tools
    "cmdline",

    # Main library for api usage
    "api",

    # Main c/c++ library for api usage
    "capi",

    # Global config constants
    "config",

    # Global utilities
    "utils",

    # Common pipeline crates
    "pipeline/common/hashes",
    "pipeline/common/io",
    "pipeline/common/minimizer_bucketing",
    "pipeline/common/kmers_transform",
    "pipeline/common/colors",
    "pipeline/common/structs",

    # Assembler pipeline
    "pipeline/assembler/assembler_minimizer_bucketing",
    "pipeline/assembler/kmers_merge",
    "pipeline/assembler",

    # Querier pipeline
    "pipeline/querier"

]

default-members = ["cmdline", "api"]


[profile.release]
debug = true
lto = "thin"
#rustflags = ["-C", "link-arg=-fuse-ld=mold"]
