[package]
authors = ["Andrea Cracco <guilucand@gmail.com>"]
edition = "2021"
name = "ggcat"
version = "0.1.0"

[dependencies]
bincode = "1.3.3"
bstr = "0.2.8"
byteorder = "1.3.2"
ctrlc = "3.1.3"
itertools = "0.10.0"
lazy_static = "1.4.0"
lz4 = "1.23.1"
nix = "0.15.0"
postcard = "0.4.2"
rayon = "1.3.0"
serde = "1.0.102"
stopwatch = "0.0.7"
structopt = "0.3.5"
hashbrown = "=0.11.2"
rand = "0.8.3"
libc = "0.2.94"
filebuffer = "0.4.0"
crossbeam = "0.8.0"
clap = "2.33.3"
parallel-processor = { path = "libs/parallel-processor-rs" }
libdeflate-rs = { path = "libs/libdeflate-rs" }
fdlimit = "0.2.1"
parking_lot = { version = "0.12.0" }
pcg_rand = "0.13.0"
dashmap = { version = "4.0.2" }
serde_json = "1.0.68"
ahash = "0.7.4"
siphasher = "0.3.7"
desse = "0.2.1"
replace_with = "0.1.7"
roaring = "0.7.0"
backtrace = "0.3.63"
csv = "1.1.6"
flate2 = { default-features = false, features = ["cloudflare_zlib"], version = "1.0.22" }
typenum = "1.15.0"
nightly-quirks = { path = "libs/nightly-quirks" }
fs_extra = "1.2.0"
atoi = "1.0.0"

[profile.release]
debug = true
lto = "fat"

[features]
mem-analysis = ["parallel-processor/track-usage"]
no-stats = ["parallel-processor/no-stats"]
process-stats = ["parallel-processor/process-stats"]

[build-dependencies]
make-cmd = "0.1.0"
