
cargo-features = ["profile-rustflags"]

[workspace]

members = [
    # Main crate for the command line tools
    "crates/cmdline",

    # Main library for api usage
    "crates/api",

    # Main c/c++ library for api usage
#    "crates/capi",

    # Global config constants
    "crates/config",

    # Global utilities
    "crates/utils",

    # Common pipeline crates
    "crates/hashes",
    "crates/io",
    "crates/minimizer_bucketing",
    "crates/kmers_transform",
    "crates/colors",
    "crates/structs",

    # Assembler pipeline
    "crates/assembler_minimizer_bucketing",
    "crates/assembler_kmers_merge",
    "crates/assembler",

    # Querier pipeline
    "crates/querier"

]

default-members = ["crates/cmdline", "crates/api"]


[profile.release]
debug = true
lto = "thin"
#rustflags = ["-C", "link-arg=-fuse-ld=mold"]
