
[workspace]

members = [
    # Main crate for the command line tools
    "cmdline",

    # Common libraries
    "libs/libdeflate-rs",
    "libs/parallel-processor-rs",
    "libs/nightly-quirks"

]


[profile.release]
debug = true
lto = "fat"
