[package]
name = "assembler_minimizer_bucketing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
config = { path = "../config" }

# Common libraries
parallel-processor = "0.1.0"
streaming-libdeflate-rs = "0.1.0"

# Static dispatch
dynamic-dispatch = "0.3.0"

# Common pipeline libraries
hashes = { path = "../hashes" }
io = { path = "../io" }
colors = { path = "../colors" }
structs = { path = "../structs" }
minimizer_bucketing = { path = "../minimizer_bucketing" }

# Other libraries
typenum = "1.15.0"

[features]
devel-build = []
