[package]
name = "kmers_merge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
config = { path = "../../../config" }
utils = { path = "../../../utils" }

# Common libraries
parallel-processor = { path = "../../../libs/parallel-processor-rs" }
streaming-libdeflate-rs = "0.1.0"
nightly-quirks = "0.1.0"

# Common pipeline libraries
hashes = { path = "../../common/hashes" }
io = { path = "../../common/io" }
colors = { path = "../../common/colors" }
structs = { path = "../../common/structs" }
kmers_transform = { path = "../../common/kmers_transform" }
minimizer_bucketing = { path = "../../common/minimizer_bucketing" }

# Dependencies
assembler_minimizer_bucketing = { path = "../assembler_minimizer_bucketing" }


# Other crates
hashbrown = "0.12.3"
typenum = "1.15.0"
crossbeam = "0.8.2"

# Profiler
instrumenter = "0.1.0"
parking_lot = "0.12.1"

[dev-dependencies]
fdlimit = "0.2.1"
rayon = "1.5.3"

