[package]
name = "hashes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hashes"

[dependencies]
serde = "1.0.145"
ahash = "0.8.0"

# Config
config = { path = "../../../config" }

# Static dispatch
static-dispatch = { path = "../../../libs/static-dispatch" }


[dev-dependencies]
pcg_rand = "0.13.0"
rand = "0.8.5"
utils = { path = "../../../utils" }


