[package]
name = "kmers_transform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
config = { path = "../../../config" }
utils = { path = "../../../utils" }

# Common libraries
parallel-processor = { path = "../../../libs/parallel-processor-rs" }
libdeflate-rs = { path = "../../../libs/libdeflate-rs" }
nightly-quirks = { path = "../../../libs/nightly-quirks" }
hashes = { path = "../hashes" }
minimizer_bucketing = { path = "../minimizer_bucketing" }

# Other libraries
io = { path = "../io" }
parking_lot = "0.12.1"
typenum = "1.15.0"
replace_with = "0.1.7"
tokio = "1.20.1"


# Tracing
instrumenter = { path = "../../../libs/instrumenter-rs" }
