[package]
name = "io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
config = { path = "../../../config" }
utils = { path = "../../../utils" }


# Common libraries
parallel-processor = "0.1.0"
streaming-libdeflate-rs = "0.1.0"
nightly-quirks = "0.1.0"

# Pipeline libraries
hashes = { path = "../hashes" }

parking_lot = "0.12.1"
byteorder = "1.4.3"
lz4 = "1.24.0"
bincode = "1.3.3"
serde = "1.0.145"
flate2 = "1.0.24"
typenum = "1.15.0"
bstr = "1.0.1"

[dev-dependencies]
rand = "0.8.5"
