[package]
name = "io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
config = { path = "../../../config" }
utils = { path = "../../../utils" }


# Common libraries
parallel-processor = { path = "../../../libs/parallel-processor-rs" }
libdeflate-rs = { path = "../../../libs/libdeflate-rs" }
nightly-quirks = { path = "../../../libs/nightly-quirks" }

# Pipeline libraries
hashes = { path = "../hashes" }

parking_lot = "0.12.1"
byteorder = "1.4.3"
lz4 = "1.23.3"
bincode = "1.3.3"
serde = "1.0.137"
flate2 = "1.0.24"
typenum = "1.15.0"
bstr = "0.2.17"

[dev-dependencies]
rand = "0.8.5"
