[package]
name = "minimizer_bucketing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Config
config = { path = "../config" }

# Common libraries
parallel-processor = "0.1.0"
streaming-libdeflate-rs = "0.1.0"
nightly-quirks = "0.1.0"

# Pipeline libraries
hashes = { path = "../hashes" }
io = { path = "../io" }

# Other libraries
replace_with = "0.1.7"
serde = "1.0.145"
bincode = "1.3.3"
typenum = "1.15.0"
parking_lot = "0.12.1"
