[package]
authors = ["Andrea Cracco <guilucand@gmail.com>"]
edition = "2021"
name = "ggcat-api"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]

# Global config
config = { package = "ggcat_config", path = "../config" }

# GGCAT main modules
assembler = { package = "ggcat_assembler", path = "../assembler" }
querier = { package = "ggcat_querier", path = "../querier" }

fdlimit = "0.2.1"
parallel-processor = "0.1.0"
rayon = "1.5.3"

